### ISSUE TITLE
Keeping any non stdmod parameters at the bottom of parameters list.

### ISSUE THREAD

**Issue by rdrgmnzs** [stdmod/puppet-elasticsearch#1]
One of the things that has frustrated me in the past is trying to find any non standard parameters amongst the standard parameters. 

As an example "$java_heap_size" in "init.pp", I would suggest that we place any such parameters after the stdmod parameters. It would make these variables easier to locate as well as keep the code a little more consistent.

**Comment by alvagante** [comment]
+1 in keeping the params separated.
In the NextGen modules I tended to place the non standard ones at the beginning, but the principle is the same.
